### ISSUE TITLE
Update Fails

### ISSUE THREAD

**Issue by AlexaVonTess** [REMnux/remnux-cli#105]
We get this often.  We are using the standard REMnux VM provided.

![image](https://user-images.githubusercontent.com/106329770/205958528-7105daf9-170a-4861-8144-6504499eb7c7.png)

**Comment by digitalsleuth** [comment]
Hi @AlexaVonTess , can you attach your saltstack.log file so we can determine the cause of the error?

**Comment by AlexaVonTess** [comment]
Yes, Sir.  I was just doing that! :)
[saltstack.log](https://github.com/REMnux/remnux-cli/files/10168000/saltstack.log)

**Comment by digitalsleuth** [comment]
It looks like the repo for Unfurl changed its default branch from master to main, and the link to the requirements file broke because of this.

I'll submit a PR to get this fixed shortly, but all of the other tools installed successfully. Once the fix is implemented you can re-run the upgrade command and it should install cleanly, but your VM is good to go right now, just doesn't have Unfurl.

**Comment by AlexaVonTess** [comment]
Thank you so much for the quick response and confirmation.

**Comment by lennyzeltser** [comment]
Thanks for the fix, @digitalsleuth. I incorporated it into the release; the issue should be corrected now, @AlexaVonTess.

**Comment by AlexaVonTess** [comment]
I just tried it and it failed.  Should I wait longer?  The log is attached.
[saltstack.log](https://github.com/REMnux/remnux-cli/files/10169563/saltstack.log)

**Comment by digitalsleuth** [comment]
Hi @AlexaVonTess are you using the `update` command, or the `upgrade` command?

**Comment by AlexaVonTess** [comment]
update

**Comment by digitalsleuth** [comment]
Please instead use the `upgrade` command. Update re-installs all of the applications at the version / config they are already at, and in this case your version is one which existed prior to the Unfurl branch change.

**Comment by AlexaVonTess** [comment]
That worked.  Thanks again.
