### ISSUE TITLE
Update returned exit code not zero error while installing REMnux as an add-on to SIFT Workstation

### ISSUE THREAD

**Issue by hantavirus69** [REMnux/remnux-cli#113]
Update returned exit code not zero error while installing REMnux as an add-on to SIFT Workstation. Screenshot of error and saltstack.log attached. 
I apologize in advance if this is a simple fix, but my Linux experience is both minimal and rusty.

![REMnux-installation_failure-2](https://user-images.githubusercontent.com/111774373/212759729-a17267bd-6017-4103-ab55-913455a71cc1.png)

**Comment by digitalsleuth** [comment]
Hi @hantavirus69 , this is an easy fix, and was caused by a recent update to Saltstack. You can run the following command first, then try your installation again:
`sudo python3 -m pip install 'importlib-metadata<5.0.0'`

Please let us know if this works for you!

**Comment by hantavirus69** [comment]
Thank you, @digitalsleuth. That fixed it, and the installation is in progress.

**Comment by hantavirus69** [comment]
I thought that fixed it, because the installation started and took quite a while but I got the same error. Any ideas, @digitalsleuth ?
![REMnux-installation-Saltstack_issue](https://user-images.githubusercontent.com/111774373/212772387-b12e8e6b-0ff0-47ea-bb64-601ff4362cb9.png)

**Comment by digitalsleuth** [comment]
Actually @hantavirus69 , the error you got is different, and it identifies an issue with the thug installation. Can you upload your saltstack.log file for this installation attempt so we can review?

Cheers!

**Comment by hantavirus69** [comment]
Here it is.
[saltstack.log](https://github.com/REMnux/remnux-cli/files/10429795/saltstack.log)

**Comment by hantavirus69** [comment]
@digitalsleuth here are the log messages as well. I had a message at boot up again today. I'm surprised to see this many issues. 
[log messages 01172023.odt](https://github.com/REMnux/remnux-cli/files/10437552/log.messages.01172023.odt)

**Comment by digitalsleuth** [comment]
Hi @hantavirus69 , while I can understand and appreciate your frustration with the install not completing successfully, the errors you're experiencing are not with the REMnux toolkit itself. 
It turns out that setuptools apparently has an issue with version 66.0 which is causing an installation issue with the 'ssdeep' package with thug. All of the other tools in REMnux installed correctly and you shouldn't have any issue with those.

As for the errors you just posted in the `log messages 01172023.odt` document, those are not caused by the REMnux installer, but instead appear to be an issue with the configuration or installation of a package called "mp4parse" and the snapcraft store. Neither of these are used by REMnux.

I will be submitting a pull request shortly to ensure the Thug issue doesn't happen again, and that should be coming shortly.

Cheers!

**Comment by hantavirus69** [comment]
@digitalsleuth Thank you. I'll see what I can figure out on the other issue.

**Comment by lennyzeltser** [comment]
Thanks for fixing the Thug issue, @digitalsleuth. I just incorporated it into a new release. @hantavirus69, you can get it by running `remnux upgrade`.

**Comment by hantavirus69** [comment]
@lennyzeltser & @digitalsleuth - Thank you both so much!

**Comment by l3fdb33f** [comment]
@lennyzeltser @digitalsleuth Hi, so I recently installed REMnux in addon mode for WSL Ubuntu 20.04 and had issues running remnux update. Your advice in this thread, namely:
> sudo python3 -m pip install 'importlib-metadata<5.0.0'

seems to have fixed my issue, but I was wondering if the saltstack workaround has been propagated correctly? Is this something everyone is dealing with or only certain installs?

**Comment by digitalsleuth** [comment]
Hi @l3fdb33f , The issue is with the way SaltStack utilizes importlib-metadata, and the fact that version 5+ of importlib-metadata has deprecated certain features (as identified [here](https://github.com/saltstack/salt/pull/62854)). Once the version containing this fix has been released, we can adjust the correct version. However the latest version (3005.1-2) does not contain this fix, so at this point we are stuck waiting.

Unfortunately, this is something everyone is dealing with.
