### ISSUE TITLE
Install failure

### ISSUE THREAD

**Issue by gratitudist** [REMnux/remnux-cli#116]
I seem to be having a similar issue to others, but the things that have been recommended in the closed issues have not worked for me. I was following the Install From Scratch directions here, https://docs.remnux.org/install-distro/install-from-scratch, and had multiple failures, see the saltstack.orig.log file, tried a few different things mentioned in closed issues to no avail. Any help appreciated.

[saltstack_logs.tgz](https://github.com/REMnux/remnux-cli/files/10728725/saltstack_logs.tgz)

**Comment by gratitudist** [comment]
It appears this may have helped, install is running now. https://github.com/REMnux/remnux-cli/issues/103#issuecomment-1312637486

**Comment by digitalsleuth** [comment]
Hi @gratitudist , the error you got the first time is actually a result of a hash value update for PolarProxy, and that we can get fixed shortly. The second issue was as a result of the importlib-metadata version not working for the installed version of Saltstack, which is fixed by 103.

I'll take a look at PolarProxy and get it updated soon!

**Comment by gratitudist** [comment]
Thank you @digitalsleuth, much obliged.

**Comment by joaogmarques** [comment]
Hi @digitalsleuth I'm having the same issue (as expected). Please update us whenever this is fixed.

Thanks for the good work!

**Comment by digitalsleuth** [comment]
Hi @joaogmarques , could you attach your saltstack.log so we can confirm it is the same issue?

**Comment by joaogmarques** [comment]
[saltstack.log](https://github.com/REMnux/remnux-cli/files/10742805/saltstack.log)

Here it is @digitalsleuth

**Comment by digitalsleuth** [comment]
Hi @joaogmarques , the issue with yours is the `importlib-metadata` issue many have been experiencing with SaltStack.

To fix this, run the following, then try the install again:
`sudo python3 -m pip install 'importlib-metadata<5.0.0'`

**Comment by joaogmarques** [comment]
@digitalsleuth you're right, my bad. I had an results.yml with errors from PolarProxy before but disappeared. Thanks

**Comment by joaogmarques** [comment]
[saltstack.log](https://github.com/REMnux/remnux-cli/files/10743014/saltstack.log)
@digitalsleuth the installation continues to break and now seems to be related with PolarProxy

**Comment by digitalsleuth** [comment]
@joaogmarques Yes at the moment that is expected, because PolarProxy recently released an update, thus the hash value has changed and is causing an error.

Everything else installed correctly though, so there should be no other problems with any other tools.

A PR is already submitted to update this then it should be good. We'll keep you posted.

**Comment by gratitudist** [comment]
Looks like the issue is resolved for me. I did a `remnux upgrade` this morning and got a `SUCCESS` message at the end of the process. Thank you for the prompt resolution!

**Comment by digitalsleuth** [comment]
Glad to help!
