### ISSUE TITLE
Upgrade failed

### ISSUE THREAD

**Issue by AGM-65** [REMnux/remnux-cli#118]
Hello all, first of all thank you very much for maintaining this project. I really appreciate it and think you all rock! I was having issues upgrading remnux from FOR610 so I pulled down a new OVA. Unfortunately I am still running into similar issues. I have followed every step from the https://docs.remnux.org/install-distro/keep-the-distro-up-to-date, plus upgraded my distro.
Set up:
![image](https://user-images.githubusercontent.com/126118839/220782517-c6471ce6-80f4-453e-832a-46e6b19f02bf.png)

Error when running remnux upgrade:
![image](https://user-images.githubusercontent.com/126118839/220782622-ebe6edb7-1aa0-478a-9def-2f86aaf16e9b.png)

Output from saltstack.log:
[saltstack.log](https://github.com/REMnux/remnux-cli/files/10808996/saltstack.log)

**Comment by digitalsleuth** [comment]
Hi @AGM-65 , the error you're receiving is only due to a recent update to PolarProxy not matching the hash we currently have in the salt states. erik4711 has recently submitted a pull request [here](https://github.com/REMnux/salt-states/pull/232) which will address the recent update.

All of the other tools and configurations have been installed correctly, so everything else will still function as intended.

**Comment by AGM-65** [comment]
Ok great, thank you for the quick response! I appreciate the work you're doing.
