### ISSUE TITLE
Remnux failing install at ChildProcess.<Anonymous>, suspected Git issue

### ISSUE THREAD

**Issue by tylerwhardy** [REMnux/remnux-cli#139]
It looks like this is the issue:

# [ERROR   ] Can't parse line 'FakeNet-NG @ git+https://github.com/fireeye/flare-fakenet-ng@ac33a706274d3e567080d261f7886fd472378ffa'
# [ERROR   ] Can't parse line 'peepdf @ git+https://github.com/digitalsleuth/peepdf.git@8b46f721f3a56c34feacf76174739167fc53a489'

[saltstack.log](https://github.com/REMnux/remnux-cli/files/12270244/saltstack.log)

This is on most recent, fully updated Ubuntu 20.04 server image being run on Proxmox using instructions from Remnux from Scratch documentation. I'll be moving over to the desktop install instructions I saw and not updating to see how that works.

**Comment by digitalsleuth** [comment]
Hi @tylerwhardy , the error you're seeing "Can't parse.." is not an error that gets accounted for in the grand scheme, so that's not the actual error which occurred.

The error you're experiencing was due to a temporary connectivity issue with `rubygems.org` when trying to install `therubyracer`. If you try again, everything should work fine, as this was only temporary.

You can see the error between lines 61582 and 61741 in the log, with the line starting with `[ERROR   ]`.

**Comment by lennyzeltser** [comment]
Closing this issue because it seems to be tied to a connectivity issue.
