### ISSUE TITLE
Error: Update returned exit code not zero on fresh install

### ISSUE THREAD

**Issue by SackOfHacks** [REMnux/remnux-cli#180]
Remnux update keeps failing with error:

>> Running: remnux-theme
>> Running: ssh
Update returned exit code not zero
Error: Update returned exit code not zero
    at ChildProcess.<anonymous> (/snapshot/remnux-cli/remnux-cli.js:571:23)
    at ChildProcess.emit (events.js:315:20)
    at maybeClose (internal/child_process.js:1021:16)
    at Process.ChildProcess._handle.onexit (internal/child_process.js:286:5)

Sometimes problems occur due to network or server issues when
downloading packages, in which case retrying your operation
a bit later might lead to good results.

To determine the nature of the issue, please review the
saltstack.log file under /var/cache/remnux/cli in the
subdirectory that matches the REMnux version you're installing.
Search for the log file for "result: false" messages and look at
the surrounding lines to diagnose the issue.

For assistance go to https://github.com/REMnux/remnux-cli/issues

I have tried redeploying the OVA and updating the remnux-cli without luck. Saltstack log is attached:

[saltstack.log](https://github.com/REMnux/remnux-cli/files/15505641/saltstack.log)

**Comment by digitalsleuth** [comment]
Hi @SackOfHacks , it looks like the only error message was related to a possibly missing file during the installation process. Can you check to see if the file `/opt/malwoverview/lib/python3.8/site-packages/root/.malwapi.conf` exists? If part of the path is missing, can you identify the part of the path that's missing?

**Comment by SackOfHacks** [comment]
Hah, seems like I was on the right path troubleshooting this. 

Here is the ls output for the directory path that is throwing an error:

remnux@remnux: $ ls /opt/malwoverview/lib/python3.8/site-packages/root/.malwapi.conf
ls: cannot access '/opt/malwoverview/lib/python3.8/site-packages/root/.malwapi.conf': **No such file or directory**
remnux@remnux: $ ls /opt/malwoverview/lib/python3.8/site-packages/root
ls: cannot access '/opt/malwoverview/lib/python3.8/site-packages/root': **No such file or directory**
remnux@remnux: $ ls /opt/malwoverview/lib/python3.8/site-packages/
backports                           geocoder  ...

There seems to be no root folder within site-packages

**Comment by digitalsleuth** [comment]
Are `backports` and `geocoder` the only folders found under the `site-packages` folder? Or are there more? If so, can you list those?

**Comment by takahiro-prog** [comment]
Hello.
I'm also having trouble with the same problem.

Since the error content was similar to @SackOfHacks , I would like to share my error as well.

I ran remnux on virutlabox, In my saltstack.log I found the following 4 falses:
```shell
remnux@remnux:/var/cache/remnux/cli/v2024.22.3$ cat saltstack.log | grep -B 4 false
    changes: {}
    comment: 'One or more requisite failed: remnux.python3-packages.remnux-python3-packages'
    duration: 0.005
    name: /etc/remnux-version
    result: false
--
    comment: Local file source /opt/malwoverview/lib/python3.8/site-packages/root/.malwapi.conf
      does not exist
    duration: 2.946
    name: /home/remnux/.malwapi.conf
    result: false
--
    changes: {}
    comment: 'One or more requisite failed: remnux.addon.remnux-addon-version-file'
    duration: 0.004
    name: remnux-dedicated
    result: false
--
    changes: {}
    comment: 'One or more requisite failed: remnux.python3-packages.malwoverview.remnux-python3-packages-malwoverview-config-file'
    duration: 0.009
    name: remnux-python3-packages
    result: false
```

By the way, under my site-packages I have the following packages included:

```shell
remnux@remnux:~$ ls /opt/malwoverview/lib/python3.8/site-packages/
backports                           peutils.py
certifi                             pip
certifi-2022.6.15.dist-info         pip-20.0.2.dist-info
charset_normalizer                  pip-20.0.2.virtualenv
charset_normalizer-2.1.0.dist-info  pkg_resources
click                               pkg_resources-0.0.0.dist-info
click-8.1.3.dist-info               pkg_resources-0.0.0.virtualenv
colorama                            polyswarm_api
colorama-0.4.5.dist-info            polyswarm_api-3.0.0.dist-info
configparser-5.2.0.dist-info        __pycache__
configparser.py                     python_dateutil-2.8.2.dist-info
dateutil                            python_magic-0.4.27.dist-info
decorator-5.1.1.dist-info           ratelim
decorator.py                        ratelim-0.1.6.dist-info
easy_install.py                     requests
future                              requests-2.28.1.dist-info
future-0.18.2.dist-info             setuptools
geocoder                            setuptools-44.0.0.dist-info
geocoder-1.38.1.dist-info           setuptools-44.0.0.virtualenv
home                                simplejson
idna                                simplejson-3.17.6.dist-info
idna-3.3.dist-info                  six-1.16.0.dist-info
libfuturize                         six.py
libpasteurize                       urllib3
magic                               urllib3-1.26.11.dist-info
malwoverview                        validators
malwoverview-5.4.4.dist-info        validators-0.20.0.dist-info
ordlookup                           _virtualenv.pth
past                                _virtualenv.py
pathlib-1.0.1.dist-info             wheel
pathlib.py                          wheel-0.34.2.dist-info
pefile-2022.5.30.dist-info          wheel-0.34.2.virtualenv
pefile.py
```
---

Also, in my error, I didn't see any packages in site-packages to begin with , but I changed /etc/remnux-version to v2024.22.3 and  I tried `rumnux update` , the package appeared in site-packages.

However, But the error in saltstack.log remained the same.

Lastly, Here are the things I tried for the `remnux upgrade` command error and the results.

1. I upgrade guest additions first, rebooted, and then run `remnux upgrade`.
Result: In addition to the above error, an error caused by draios was displayed. (Sorry, I don't remember what kind of error was related to draios. I deleted the remnux vm, re-imported it, and repeated the process, so I don't have the log at hand.)

2. Run `sudo apt -y update && sudo apt -y upgrade` before `remnux upgrade` command
Result: Same error as above.

3. Comment out `/etc/apt/sources.list.d/draios.list` and run `remnux upgrade`
Result: Same error as above.

4. Set `timezonectl` in my timezone and run it
Result: Same error as above.

5. Rewrite `/etc/remnux-version` to the latest `v2024.22.3` and then run `remnux update`
Result: Same error as above, but packages under site-packages were added.

**Comment by digitalsleuth** [comment]
Hi @takahiro-prog and @SackOfHacks , this issue seems to have been introduced by a change in the build of malwoverview since v5.4.3. Whether or not this is going to be a permanent change will depend on the author, but I have raised [this issue](https://github.com/alexandreborges/malwoverview/issues/43) with the author to inform them of the noted change, and once we hear back from them, we will adjust accordingly.

Cheers!

**Comment by digitalsleuth** [comment]
@takahiro-prog If you happen to be having other issues besides just the re-location of that file, please let us know and share your saltstack.log file with us so we can assist.

**Comment by takahiro-prog** [comment]
Hi @digitalsleuth, Other than this error, I haven't had any problems.
If I find another error, I'll report it in another Issue.

Thanks!

**Comment by SackOfHacks** [comment]
@digitalsleuth and others here, I fixed the problem by creating the root folder under  /opt/malwoverview/lib/python3.8/site-packages/, followed by a "touch /opt/malwoverview/lib/python3.8/site-packages/root/.malwapi.conf". After that "remnux upgrade" completes normally.

**Comment by lennyzeltser** [comment]
@SackOfHacks, FYI, I just adjusted the state file for malwoverview to match the new location of the .malwapi.conf file, so the error shouldn't occur when people run `remnux upgrade`.
