### ISSUE TITLE
Error When Manually Installing REMnux on Ubuntu 20.04 KVM/QEMU

### ISSUE THREAD

**Issue by K3lvinRob3rt** [REMnux/remnux-cli#186]
Hi, I had to open a fresh request as most of the issues are quite different from mine. 
So, I've attempted to install  REMnux on Ubuntu 20.04 inside KVM/QEMU several times, but ended with the same errors, I will really appreciate some help. I've tried with both the mini iso and full desktop iso of Ubuntu 20.04

```
>> Running: wireshark
>> Running: remnux-theme
>> Running: ssh
Update returned exit code not zero
Error: Update returned exit code not zero
    at ChildProcess.<anonymous> (/snapshot/remnux-cli/remnux-cli.js:571:23)
    at ChildProcess.emit (events.js:315:20)
    at maybeClose (internal/child_process.js:1021:16)
    at Process.ChildProcess._handle.onexit (internal/child_process.js:286:5)
```

Here is my saltstack file. Thanks in advance.
[saltstack.log](https://github.com/user-attachments/files/16276639/saltstack.log)

**Comment by digitalsleuth** [comment]
Hi @K3lvinRob3rt , it looks like the only errors in your installation were due to connectivity issues during the git clone and installation of both the "thug" and "volatility (python 2)" packages. If you attempt the installation again, these two should install properly. If, however, you are behind a proxy, you may want to consider reviewing [this section](https://docs.remnux.org/tips/remnux-config-tips#behind-proxy) of the REMnux docs which should help you.

Please let us know how this goes.

Cheers!

**Comment by K3lvinRob3rt** [comment]
Thank you so much @digitalsleuth, you are right, I re-run the installation at night time and it was successful. Thank you, I really appreciate your response on this.
