### ISSUE TITLE
SSH Error with Bionic/Focal VirtualBox OVAs

### ISSUE THREAD

**Issue by marcus-cr** [REMnux/remnux-cli#21]
Receiving the following message with `remnux update` command on Ubuntu 18.04 (Bionic) OVA file for VirtualBox:

```
>> Running: ssh
Update returned exit code not zero
Error: Update returned exit code not zero
    at ChildProcess.<anonymous> (/snapshot/remnux-cli/remnux-cli.js:568:23)
    at ChildProcess.emit (events.js:315:20)
    at maybeClose (internal/child_process.js:1021:16)
    at Socket.<anonymous> (internal/child_process.js:443:11)
    at Socket.emit (events.js:315:20)
    at Pipe.<anonymous> (net.js:674:12)
```

Issue also seems to occur with the Ubuntu 20.04 (Focal) OVA file for VirtualBox as well. Here's the [saltstack.log](https://github.com/REMnux/remnux-cli/files/5777913/saltstack.log) file for Bionic.

Nothing is produced with `grep -i -B5 "result: false"`:

```
remnux@remnux:~$ cat /var/cache/remnux/cli/v2020.51.8/saltstack.log | grep -i -B5 "result: false"
Binary file (standard input) matches
```

**Comment by lennyzeltser** [comment]
Hi, @marcus-cr. The saltstack.log file suggests network connectivity issue. For example:

```
Could not resolve 'us.archive.ubuntu.com'
```
Could you please confirm that you can access the internet from within the VM?

**Comment by marcus-cr** [comment]
@lennyzeltser It appears that I did not have internet access initially. Had to change `resolv.conf` to include a nameserver other than 127.0.0.53. Was able to update properly now. 

Is there a recommended configuration? Usually I use two interfaces: one as NAT for internet access to update and another as host-only.

The OVA file imported a single interface as NAT but the `resolv.conf` file defaulted to the 127.0.0.53 nameserver and does not persist with reboot.

**Comment by lennyzeltser** [comment]
I suspect most people just use the default configuration of the REMnux VM, keeping the VM in NAT mode. Your approach of using the REMnux VM as a gateway between your other VMs and the internet is solid, but I haven't had a chance to document best practices for doing this. Maybe Ubuntu prefers other ways of defining name servers instead of modifying `resolv.conf`, but I haven't had a chance to look into it.

Marco Figueroa just published [detailed instructions for setting up a malware analysis lab](https://labs.sentinelone.com/building-a-custom-malware-analysis-lab-environment/), which includes a similar configuration for the REMnux VM. Take a look, perhaps his instructions will be of help?

**Comment by marcus-cr** [comment]
Those instructions do help, but any changes I make to get the second interface configured and running doesn't persist after reboot. I'm assuming I need to edit `/etc/netplan/01-netcfg/yaml` since `/etc/network/interfaces` doesn't exist?

Also, it seems that the VM won't update properly out of the box. I'm able to ping external IPs, such as Google's 8.8.8.8 DNS, but any DNS lookup always using the 127.0.0.53 nameserver. I have to manually add a nameserver to resolver.conf after every reboot, unless there is another file I'm overlooking.

**Comment by accidentalrebel** [comment]
I am getting the same error when running `remnux update`. This happens even after a fresh import of Remnux to a virtual machine.

> I suspect most people just use the default configuration of the REMnux VM, keeping the VM in NAT mode

Even if I change to Bridged, this problem still happens.

**Comment by lennyzeltser** [comment]
@accidentalrebel, please share your saltstack.log file, so we can take a look what's happening.

**Comment by accidentalrebel** [comment]
Hello @lennyzeltser,

Here is my saltstack.log file. 
[saltstack.log](https://github.com/REMnux/remnux-cli/files/5916369/saltstack.log)

There are a number of instances that had `result: false` but this one caught my eye:
```
   pip_|-remnux-python3-packages-volatility3_|-git+https://github.com/volatilityfoundation/volatility3.git@master_|-installed:
    __id__: remnux-python3-packages-volatility3
    __run_num__: 328
    __sls__: remnux.python3-packages.volatility3
    changes: {}
    comment: "Failed to install packages: git+https://github.com/volatilityfoundation/volatility3.git@master.
      Error: Collecting git+https://github.com/volatilityfoundation/volatility3.git@master\n
      \ Cloning https://github.com/volatilityfoundation/volatility3.git (to revision
      master) to /tmp/pip-req-build-15wwup7d   Running command git clone -q https://github.com/volatilityfoundation/volatility3.git
      /tmp/pip-req-build-15wwup7d\n  WARNING: Did not find branch or tag 'master',
      assuming revision or ref.\n  Running command git checkout -q master\n  error:
      pathspec 'master' did not match any file(s) known to git\nERROR: Command errored
      out with exit status 1: git checkout -q master Check the logs for full command
      output."
    duration: 7124.794
    name: git+https://github.com/volatilityfoundation/volatility3.git@master
    result: false
    start_time: '00:37:41.270703'
```
So it seems that there is a problem installing volatility3 because the master branch does not exist on it's github repo: https://github.com/volatilityfoundation/volatility3

To fix this I edited `volatility3.sls` and changed `volatility3.git@master` to `volatility3.git@stable`. But if I run `remnux update` my changes get overwritten.

Any tips on how I could fix this?

Thanks!

**Comment by lennyzeltser** [comment]
@accidentalrebel, you're right about the nature of the problem you encountered. I had corrected the issue a few days ago in [volatility.sls](https://github.com/REMnux/salt-states/blob/master/remnux/python3-packages/volatility3.sls), so it should be addressed for everyone. To make sure you get the latest state files, use the `remnux upgrade` command (instead of `remnux update`).
