### ISSUE TITLE
Trouble updating at the Error loading module.boto3_elasticsearch: __init__ failed corral

### ISSUE THREAD

**Issue by Juancho3884** [REMnux/remnux-cli#24]
Hello!

New to malware analysis and I currently am running an update via remnux. I appear to be failing the update and I am not sure how to remedy the situation so that i can start to break apart things.... Attached I have the Saltstack.log
[saltstack.log](https://github.com/REMnux/remnux-cli/files/5934336/saltstack.log)

Thank you in advance!

Juancho

**Comment by lennyzeltser** [comment]
Hi, @Juancho3884. Looks like you encountered an issue that we recently corrected. It's related to the way Volatility3 names its branches. It should get automatically fixed for you if you run the `remnux upgrade` command.

**Comment by Juancho3884** [comment]
Good afternoon!

Thank you so much for this assistance, I ran the command and upon rebooting was presented with a guru error message. After closing down the VM and turning it back on, it wouldn't let me get past authentication. I would authenticate correctly (after trying non valid then valid credentials for comparison), but then the vm appears to do some form of crashing and the authentication prompt reappears. 

At this point would it be best to not reboot the VM and attempt to update/ download specific tools or is there a good way around the guru message?

I am recreating the error now to paste the information

**Comment by digitalsleuth** [comment]
Hi @Juancho3884 , it's possible there's a permissions error with the contents of your /home folder. In your VM, you can attempt to go to another TTY (CTRL-ALT-F3 for example) and log in from there. 

Once logged in, run `ls -la` and check the permissions on all files in your home directory. If any of them are not owned by the user you're attempting to log in as, change the ownership on those files to match that user. Then reboot and try again.

Give this a shot and let us know how it turns out.

**Comment by Juancho3884** [comment]
Hello @digitalsleuth, i think you were right. i entered tty and after seeing root assigned to .cpan and .. i changed them both to default remnux, rebooted and was able to log in. I had then updating again, and rebooted several times to proof any issues and it appears like everything works! 

Thank you a ton for your assistance
