### ISSUE TITLE
WSL 2 18.04 Ubuntu Install - SaltStack Errors

### ISSUE THREAD

**Issue by 5iri5** [REMnux/remnux-cli#36]
Hi

Tried installing WSL2 using 18.04 Ubuntu & hit into errors. Not very linux savvy, struggling to work my way round in addressing the problem.

I've attached grep searches of 'False' and 'ERROR' from the SaltStack log - please can you advise?

[error.txt](https://github.com/REMnux/remnux-cli/files/6657951/error.txt)
[false.txt](https://github.com/REMnux/remnux-cli/files/6657952/false.txt)
[false2.txt](https://github.com/REMnux/remnux-cli/files/6657953/false2.txt)

**Comment by digitalsleuth** [comment]
Hi @5iri5 , it looks like it might be an issue with Python 3 and keyrings / keyrings.alt. Could you provide the full saltstack.log for context?

**Comment by 5iri5** [comment]
[saltstack.log](https://github.com/REMnux/remnux-cli/files/6660398/saltstack.log)

Attached

**Comment by digitalsleuth** [comment]
Hi @5iri5 , sorry for the delay in getting back to you. It appears that there were a few different issues during this install, which may have compounded. The first is an issue installing vivisect due to the pyasn1-modules not being uninstalled, then a couple of issues with git, and the NetworkMiner hash value was incorrect. 

I'm working through each of these issues, and should have a solution today.

**Comment by digitalsleuth** [comment]
Hi @5iri5 , I've submitted a couple of pull requests which, once merged, should rectify your issues. I was unable to duplicate the git issues or the python keyring issue which came up, but I suspect they won't resurface. Once the new version is released, I would suggest trying it again, making sure that if you're using WSL 2, to use the --mode=addon command.

**Comment by lennyzeltser** [comment]
Thanks for the fixed, @digitalsleuth!

@5iri5, the version that includes @digitalsleuth's correction is now released. Please try your installation again.
