### ISSUE TITLE
sudo remnux install --mode=addon & remnux install/upgrade failing

### ISSUE THREAD

**Issue by baileys20055** [REMnux/remnux-cli#47]
Hello, 

I am trying to install from a new SANS sift ova as an addon and the install keeps failing. Please see attached SaltStack.log. I have tried multiple things from peoples previous issues with no luck. Any help would be appreciated. Thank you. 
[saltstack.log](https://github.com/REMnux/remnux-cli/files/7255920/saltstack.log)

**Comment by digitalsleuth** [comment]
Good evening @baileys20055 , it looks like there were some connection issues during your installation, mostly tied to either DNS lookup or SSL certificate failure. Are you possibly installing behind a proxy?

From the look of the rest of the log, everything else installed correctly and without issue, however only PolarProxy and NetworkMiner didn't properly install. This issue could be due to a proxy, or since both happen to be from netresec.com, there should have been some connectivity issues.

If you are behind a proxy, you could possibly try [this solution](https://docs.remnux.org/tips/remnux-config-tips#behind-proxy). I'll take a look at those two tools and see if there's an issue with the download process without a proxy to confirm.

**Comment by baileys20055** [comment]
This worked for me thank you!
