### ISSUE TITLE
SIFT + Remnux installer ubuntu 18.04 workstation

### ISSUE THREAD

**Issue by delbs27** [REMnux/remnux-cli#5]
Hi, Thanks for updating Remnux, looks amazing from what i have tried within the .ova

I have a fresh ubuntu workstation 18.04.5 install on a workstation. I have installed the latest sift workstation cli package and that installed with 0 errors.

following through the SANS article of installing Remnux alongside SIFT i receive the below error. 

>> Running: remnux-perl-packages
Update returned exit code not zero
Error: Update returned exit code not zero
    at ChildProcess.<anonymous> (/snapshot/remnux-cli/remnux-cli.js:551:23)
    at ChildProcess.emit (events.js:315:20)
    at maybeClose (internal/child_process.js:1021:16)
    at Process.ChildProcess._handle.onexit (internal/child_process.js:286:5)

Try rebooting your system and trying the operation again.

Sometimes problems occur due to network or server issues when
downloading packages, in which case retrying your operation
a bit later might lead to good results.

To determine the nature of the issue, please review the
saltstack.log file under /var/cache/remnux/cli in the
subdirectory that matches the REMnux version you're installing.
Pay particular attention to lines that start with [ERROR].

I have also uploaded the saltstack installer log file

Happy to try do some testing and provide feedback 

[saltstack_remnux_install.log](https://github.com/REMnux/remnux-cli/files/5080130/saltstack_remnux_install.log)

**Comment by lennyzeltser** [comment]
Thanks for letting me know about the issue. Would you be able to share the whole /var/cache/remnux/cli/v2020.33.2/saltstack.log file?

**Comment by delbs27** [comment]
Sure thing here it is 



[saltstack.tar.gz](https://github.com/REMnux/remnux-cli/files/5080535/saltstack.tar.gz)

**Comment by lennyzeltser** [comment]
Looks like there were issues configuring two tools: Radare2 and ipwhois. I believe I addressed them. Please run `remnux upgrade` to try.

### Radare2

The issue was the remnants of the older Radare2 libraries that SIFT installed. I modified the corresponding Salt state file on REMnux to address this automatically by removing those old packages. 

### ipwhois

An old version of ipwhois was installed by SIFT and REMnux wasn't upgrading it. I modified the corresponding Salt state file on REMnux to force the upgrade.

**Comment by delbs27** [comment]
>> COMPLETED SUCCESSFULLY! Success: 625, Failure: 0

Thank you! :D
