### ISSUE TITLE
Can't install on ubuntu 18.04 from terminal

### ISSUE THREAD

**Issue by rersheed** [REMnux/remnux-cli#52]
>> Running: apt-get autoremove -y
>> Running: /etc/ssh/sshd_config
>> Running: /etc/ssh/sshd_config
>> Running: /etc/ssh/sshd_config
>> Running: /etc/ssh/sshd_config
>> Running: /etc/ssh/sshd_config
>> Running: /etc/ssh/sshd_config
>> Running: away-from-the-dog
>> Running: echo "wireshark-common wireshark-common/install-setuid select True"| debconf-set-selections; dpkg-reconfigure -f noninteractive wireshark-common
>> Running: wireshark
>> Running: ssh

Update returned exit code not zero
Error: Update returned exit code not zero
    at ChildProcess.<anonymous> (/snapshot/remnux-cli/remnux-cli.js:569:23)
    at ChildProcess.emit (events.js:315:20)
    at maybeClose (internal/child_process.js:1021:16)
    at Process.ChildProcess._handle.onexit (internal/child_process.js:286:5)

Sometimes problems occur due to network or server issues when
downloading packages, in which case retrying your operation
a bit later might lead to good results.

To determine the nature of the issue, please review the
saltstack.log file under /var/cache/remnux/cli in the
subdirectory that matches the REMnux version you're installing.
Search for the log file for "result: false" messages and look at
the surrounding lines to diagnose the issue.

For assistance go to https://github.com/REMnux/remnux-cli/issues

**Comment by rersheed** [comment]
[saltstack.log](https://github.com/REMnux/remnux-cli/files/7491342/saltstack.log)

**Comment by digitalsleuth** [comment]
HI there @rersheed, it looks like during your install that you lost internet connectivity. There are a few error messages stating that it couldn't reach certain websites or the APT package manager couldn't reach resources. Perhaps check your internet connection and try again, that should resolve the errors.

If it doesn't, please reach out again with your new saltstack.log and we can assist.

Cheers!

**Comment by rersheed** [comment]
@binhxe  I tried again. Below is the new saltstack.log file
[saltstack.log](https://github.com/REMnux/remnux-cli/files/7502397/saltstack.log)

**Comment by lennyzeltser** [comment]
@rersheed, looks like everything installed fine now except ViperMonkey.

ViperMonkey failed because of a local directory permission issue, I think. You might be able to get around it by making sure your user `haroun` is the owner of all the files under `/home/haroun/.cache/pip`. One way to do this is to run:

```
chown -R haroun:haroun /home/haroun/.cache/pip
```

Then try the REMnux installation by running `remnux upgrade` on your existing system. If the installer responds that there is no new version of the distro, then run `remnux update`.

**Comment by rersheed** [comment]
@lennyzeltser 
I just tried again by running `sudo remnux upgrade` but it is still stopping at the point of ViperMonkey with the same information. Below is the saltstack.log file. 
[saltstack.log](https://github.com/REMnux/remnux-cli/files/7508493/saltstack.log)
.

**Comment by lennyzeltser** [comment]
Hmm... You shouldn't need to specify `sudo` before `remnux upgrade`. I'm wondering whether `sudo` is what causes the permission issue. Could you please try again:

```
chown -R haroun:haroun /home/haroun/.cache/pip
```

And then `remnux upgrade` or `remnux update` (without `sudo`)?

**Comment by rersheed** [comment]
@lennyzeltser I did all what said but it is still stopping at the ViperMonkey installation. Below is the new saltstack.log
[saltstack.log](https://github.com/REMnux/remnux-cli/files/7512965/saltstack.log)

**Comment by lennyzeltser** [comment]
This time I believe there were network access errors, for instance a timeout trying to connect to files.pythonhosted.org.

I recommend using your system as is, since even if you get an occasional error upgrading it, almost all the tools are installed and being updated fine. Maybe check permissions of the `/home/haroun/.cache/pip` directory to make sure it's owned by `haroun` and run `remnux upgrade` without `sudo`.

**Comment by R1simo** [comment]
Hello all,

I have the same exact problem as described on the main post. I checked pip folder on the /home/remnux/.cache/ folder, but there was none. I even created pip folder with correct permissions and tried `remnux upgrade` but did not work. My internet connection is stable and I have tried upgrade process on 2 different access points, but no luck. Below, I have attached my log file. 
[saltstack.log](https://github.com/REMnux/remnux-cli/files/7515153/saltstack.log)

**Comment by lennyzeltser** [comment]
@R1simo, based on the saltstack.log, the issue you encountered was unrelated: For some reason downloading pyinstxtractor.py produced an unexpected hash value of the file, which caused the installation or upgrade of that tool to fail.

**Comment by rersheed** [comment]
@lennyzeltser, I ran `ls -al /home/haroun/.cache/ | grep pip` to check the permission and it is owned by haroun which returned `drwxrwxr-x   4 haroun haroun  4096 Nov  8 22:31 pip` . When I try to run `remnux upgrade`, it tells me that remnux not installed
> remnux-cli@1.3.3.0.g1df38b1
> remnux-version: notinstalled
[saltstack.log](https://github.com/REMnux/remnux-cli/files/7516476/saltstack.log)

**Comment by lennyzeltser** [comment]
@rersheed and @R1simo:

As I review your saltstack.log files (thanks for supplying them), I have a feeling that the PIP errors are just warnings are are not the reasons why the REMnux updater produces an error at the end. In some cases, the errors are due to network connectivity problems.

@rersheed, I now see that there's this error installing ViperMonkey:

```
File
      \"/tmp/easy_install-XhhWEt/pytest-runner-5.3.1/temp/easy_install-11pnUX/setuptools_scm-6.3.2/setup.py\",
      line 22\n        f\"{type(self).__name__} is forbidden, \"\n                                              ^\n
      \   SyntaxError: invalid syntax\n   
```

I'm not sure what this is about at this point and I'm unable to replicate this condition on my system. @digitalsleuth, perhaps you can take a look and determine the nature of the issue?

**Comment by R1simo** [comment]
> As I review your saltstack.log files (thanks for supplying them), I have a feeling that the PIP errors are just warnings are are not the reasons why the REMnux updater produces an error at the end. In some cases, the errors are due to network connectivity problems.

@lennyzeltser oh okay, thank you for the reply. I will retry later today to see if it works

**Comment by digitalsleuth** [comment]
@lennyzeltser Will do!

**Comment by digitalsleuth** [comment]
So I've taken a look at the saltstack logs, and @R1simo your issue should be resolved with the recent update @lennyzeltser made.

@rersheed Yours is a little more perplexing. Can you run the following commands and paste the results?
`which python`
`which python2`
`which python3`
`cd /home/haroun && ls -la`
`python2 -m pip show setuptools`
`python3 -m pip show setuptools`

Thanks!
