### ISSUE TITLE
Error adding REMnux to an existing system

### ISSUE THREAD

**Issue by mhamouei** [REMnux/remnux-cli#56]
After spending hours trying to install REMnux on Ubuntu 20 in addon mode, still getting the same error:
`>> Running: remnux-perl-packages
Update returned exit code not zero
Error: Update returned exit code not zero
    at ChildProcess.<anonymous> (/snapshot/remnux-cli/remnux-cli.js:569:23)
    at ChildProcess.emit (events.js:315:20)
    at maybeClose (internal/child_process.js:1021:16)
    at Process.ChildProcess._handle.onexit (internal/child_process.js:286:5)
`
the log file is attached for detailed error
[saltstack.log](https://github.com/REMnux/remnux-cli/files/7790238/saltstack.log)
.

**Comment by digitalsleuth** [comment]
@mhamouei It looks like the only reason for the error is that the pyinstaller-extractor hash has changed, indicating a newer version. I'm submitting a pull request to fix this right now. Otherwise, the rest of your installation worked as it should, and you have a fully functional REMnux, with the exception of pyinstaller-extractor.

**Comment by mhamouei** [comment]
> @mhamouei It looks like the only reason for the error is that the pyinstaller-extractor hash has changed, indicating a newer version. I'm submitting a pull request to fix this right now. Otherwise, the rest of your installation worked as it should, and you have a fully functional REMnux, with the exception of pyinstaller-extractor.

Thanks @digitalsleuth

**Comment by lennyzeltser** [comment]
Thanks for reporting this, @mhamouei. Thanks for fixing this, @digitalsleuth.

The updated version of REMnux includes the correction.
