### ISSUE TITLE
Upgrade issue.

### ISSUE THREAD

**Issue by allabert** [REMnux/remnux-cli#62]
Upgrade ends with error below.

>> Running: ssh
Update returned exit code not zero
Error: Update returned exit code not zero
    at ChildProcess.<anonymous> (/snapshot/remnux-cli/remnux-cli.js:568:23)
    at ChildProcess.emit (events.js:315:20)
    at maybeClose (internal/child_process.js:1021:16)
    at Process.ChildProcess._handle.onexit (internal/child_process.js:286:5)

**Comment by lennyzeltser** [comment]
Thanks for reporting the issue. If you upload your saltstack.log file, I will be glad to review it to identify the issue. The error message itself, unfortunately, doesn’t have enough details.

**Comment by allabert** [comment]
[saltstack.log](https://github.com/REMnux/remnux-cli/files/7997977/saltstack.log)
Log uploaded.

**Comment by lennyzeltser** [comment]
@allabert, there were a few failed connections to GitHub due to network timeouts. 

Here's one:

`Error: HTTP 599: Timeout while connecting reading https://github.com/accidentalrebel/shcode2exe/raw/master/shcode2exe.py`

And here's the other:

`Error: HTTP 599: Stream closed reading https://github.com/SocialExploits/fakedns/raw/main/fakedns.py`

Besides these two tools, the others installed fine.

I suggest retrying the operation later.
