### ISSUE TITLE
Install error on fresh instance of ubuntu 20.04

### ISSUE THREAD

**Issue by Raskolnikov007** [REMnux/remnux-cli#84]
Hi there, I have been getting the same error when trying to install remnux on a fresh install of ubuntu 20.04 I've tried about 12 times and each time I get:

Error: Update returned exit code not zero
       at ChildProcess.<annonymous> (/snapshot/remnux-cli/remnux-cli.js:569:23)
       at ChildProcess.emit (events.js:315:20)
       at maybeClose (internal/child_process.js:1021:16)
       at Process.ChildProcess._handle.onexit (internal/child_process.js:286:5)

There seem to be 6 'result: false' occurrences most of which I think relate to polarproxy.

Would you be able to assist please?
[saltstack.log.txt](https://github.com/REMnux/remnux-cli/files/8939196/saltstack.log.txt)

**Comment by lennyzeltser** [comment]
@Raskolnikov007. You're right, the issue is with the PolarProxy installation. Specifically, the REMnux installer was unable to download it due to this network error:

```
Error:
      HTTP 599: Connection closed reading / 
```

I noticed that the servers hosting PolarProxy sometimes cause timeouts. I recommend trying the operation (`remux upgrade`) in a few days. Everything else installed correctly, it seems, so PolarProxy is the only tool that encounter an issue during your installation.

**Comment by Raskolnikov007** [comment]
Thanks Lenny
