### ISSUE TITLE
Unable to install on new instance of Ubuntu 20.04

### ISSUE THREAD

**Issue by Raskolnikov007** [REMnux/remnux-cli#91]
Hi there - I've been trying several times a day for a few days now to install REMnux on a fresh installation of Ubuntu 20.04. It fails each time, looking at the log I'm getting 6 'result: false' occurrences,and 5 are to do with Polar Proxy,one relates to 'remnux.tools.remnux-tools' - any assistance would be greatly appreciated! 

[saltstack (1).log](https://github.com/REMnux/remnux-cli/files/9099067/saltstack.1.log)

**Comment by digitalsleuth** [comment]
Hi @Raskolnikov007 , the error is due to an issue with the PolarProxy server, and not the installation.
```bash
[ERROR   ] Failed to cache https://www.netresec.com/?download=PolarProxy: Error: HTTP 599: Connection closed reading /
```

Unfortunately, there isn't anything that we can do to resolve or prevent this issue, as it is a server side error. However, after reviewing your log, everything else has installed correctly, with the exception of PolarProxy. 

If you wish to attempt to download it manually, you can install it within REMnux by following these steps:
- unzip the archive to `/usr/local/polarproxy`
- create a new file in the /usr/local/bin directory named `polarproxy` with the following contents
```bash
#!/bin/bash
/usr/local/polarproxy/PolarProxy ${*}
```
- `sudo chmod +x /usr/local/bin/polarproxy`

I hope this helps!

**Comment by Raskolnikov007** [comment]
Thank you, digitalsleuth!
