### ISSUE TITLE
Update Fails at SSH

### ISSUE THREAD

**Issue by redsh1rt** [REMnux/remnux-cli#94]
Hello,

I've downloaded and added the remnux OVA to VirtualBox, but I can't seem to update it properly. I've tried numerous times this morning, and the updater keeps failing at SSH:

``` bash
>> Running: ssh
Update returned exit code not zero
Error: Update returned exit code not zero
    at ChildProcess.<anonymous> (/snapshot/remnux-cli/remnux-cli.js:569:23)
    at ChildProcess.emit (events.js:315:20)
    at maybeClose (internal/child_process.js:1021:16)
    at Process.ChildProcess._handle.onexit (internal/child_process.js:286:5)
```
Here are my remnux-cli and remnux versions

``` bash
> remnux-cli@1.3.4.2.g87c65ef
> remnux-version: v2021.15.2
```
I'm never able to get to the v2022.28.1 version that *remnux upgrade* attempts to install.

I've tried redownloading remnux-cli, and used *remnux upgrade* numerous times. I've looked through other closed issues, but nothing I've tried seems to resolve this. Attached is my saltstack.log file.
[saltstack.log](https://github.com/REMnux/remnux-cli/files/9245031/saltstack.log)

Thanks in advance.

**Comment by lennyzeltser** [comment]
@redsh1rt, looks like everything upgraded fine except one tool--PolarProxy. The issue was likely due to the PolarProxy taking too long to handle the download request.

Here are the relevant lines from saltstack.log:

```
comment: 'Failed to cache https://www.netresec.com/?download=PolarProxy: Error:
      HTTP 599: Connection closed reading /'
```

Don't worry and keep using your REMnux system. Consider running `remnux upgrade` again in a few days or week, and the PolarProxy upgrade will eventually succeed.
