### ISSUE TITLE
Install from scratch failing

### ISSUE THREAD

**Issue by sameerthamke** [REMnux/remnux-cli#95]
I am following steps over [here ](https://docs.remnux.org/install-distro/install-from-scratch ) for installing REMnux from scratch, however its failing to install with below issue:

I am using VirtualBox 6.1. Also have disabled Hyper-V. Here is the saltstack log file [saltstack.log](https://github.com/REMnux/remnux-cli/files/9422513/saltstack.log) and logs from console [console.log](https://github.com/REMnux/remnux-cli/files/9422512/console.log)

**Comment by sameerthamke** [comment]
Errors are related to networkminer, PolarProxy and remnux.theme

Also there are issue related to resolution of https://www.netresec.com/?download=NetworkMiner and https://www.netresec.com/?download=PolarProxy, however same works fine on my host system.

Is there any way to point the installer at these offline downloaded packages or maybe will it detect if they are installed already offline ?

**Comment by digitalsleuth** [comment]
Hi @sameerthamke , You're correct in that the errors were caused by NetworkMiner and PolarProxy, and it appears the issue was just a temporary failure in DNS. We have seen this and other errors with the netresec website frequently, but unfortunately those errors are not caused by the installer.

There are many challenges with having the installer point to an offline location, so that won't likely be a feasible option. As for detecting the installation, that would be slightly easier to resolve, but if the installed version is older than the available version, then the same issue would arise.

I've got a couple of ideas on how we might resolve this. I'll keep you posted.

**Comment by sameerthamke** [comment]
Thank you @digitalsleuth, let me know.

**Comment by digitalsleuth** [comment]
Hi @sameerthamke sorry for the delay with this. I haven't been able to find a good solution to resolve this, as the reliability of the server providing the files is the key issue. The only available option might be to download and store the files within the salt states release itself, which can get bulky.

I'll discuss this with @lennyzeltser and see if it might be worth doing or not.
