### ISSUE TITLE
Install failing on Ubuntu 20.04

### ISSUE THREAD

**Issue by vdhal** [REMnux/remnux-cli#97]
I've been trying to install REMnux on Ubuntu 20.04 , and it keeps failing with this error:

![image](https://user-images.githubusercontent.com/22720591/189106780-5a13ede3-d58b-42bb-ac33-4fefa130420b.png)

Here's the saltstack.log file

[remnux1.log](https://github.com/REMnux/remnux-cli/files/9526297/remnux1.log)

Though I see many tools are installed and working but when i check the version, it says 'not installed

**Comment by digitalsleuth** [comment]
Hi there @vdhal , it looks like the issue was a drop in your internet connection part way through the installation. It looks like it only lasted a short time, but it did affect the installation of ViperMonkey and thug.

There was another error related to mitmproxy, in which the server was temporarily unavailable (that one was server side, Error 503), and another issue with "didierstevens.com" which appeared to also have connectivity issues, and did not successfully download that suite of tools.

The final error appears to have been a permissions error when setting up the Terminal Profile.

Due to the connectivity issues you had before, I recommend re-running the installation, but before you do, confirm that the permissions of the files in your home directory (the /home/remnux directory) are all set correctly as well.

Once you've had a chance to do that, let us know if this worked.
Cheers!

**Comment by vdhal** [comment]
[remnux.log](https://github.com/REMnux/remnux-cli/files/9526904/remnux.log)

Thanks for looking into this. 

I tried it again and it failed with the same error message, the errors in the logs too looks the same to me.

**Comment by digitalsleuth** [comment]
Hi @vdhal , they do indeed look like the same errors. Can you tell me if you're currently running this install behind a proxy?

**Comment by vdhal** [comment]
yeah, looks like proxy issue.  Thank you
